export const mockDevices = [
  {
    id: 1,
    macAddress: "00:1A:2B:3C:4D:5E",
    ipAddress: "192.168.1.10",
    hostname: "DESKTOP-OFFICE",
    vendor: "Intel Corporate",
    probableOs: "Windows 11",
    status: "ALLOWED",
    lastSeen: new Date(),
  },
  {
    id: 2,
    macAddress: "00:0C:29:4F:71:A2",
    ipAddress: "192.168.1.45",
    hostname: "kali-linux",
    vendor: "VMware, Inc.",
    probableOs: "Kali Linux",
    status: "QUARANTINED",
    lastSeen: new Date(Date.now() - 1000 * 60 * 15),
  },
  {
    id: 3,
    macAddress: "A4:D1:8C:F3:B2:D1",
    ipAddress: "192.168.1.12",
    hostname: "iPhone-14",
    vendor: "Apple, Inc.",
    probableOs: "iOS 17",
    status: "ALLOWED",
    lastSeen: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: 4,
    macAddress: "3C:71:BF:82:D3:44",
    ipAddress: "192.168.1.88",
    hostname: "Unknown-IoT",
    vendor: "Espressif Inc.",
    probableOs: "Embedded RTOS",
    status: "BLOCKED",
    lastSeen: new Date(Date.now() - 1000 * 60 * 120),
  },
  {
    id: 5,
    macAddress: "00:15:5D:01:0A:22",
    ipAddress: "192.168.1.5",
    hostname: "SERVER-PROD",
    vendor: "Microsoft Corp.",
    probableOs: "Windows Server 2022",
    status: "ALLOWED",
    lastSeen: new Date(),
  },
];

export const mockAlerts = [
  {
    id: 1,
    macAddress: "00:0C:29:4F:71:A2",
    alertType: "NEW_UNKNOWN_DEVICE",
    subject: "Security Alert: Unauthorized Device Detected",
    body: "A new device with MAC 00:0C:29:4F:71:A2 has been detected and automatically quarantined.",
    status: "PENDING",
    createdAt: new Date(Date.now() - 1000 * 60 * 2),
  },
  {
    id: 2,
    macAddress: "3C:71:BF:82:D3:44",
    alertType: "BLOCKED_RECONNECT",
    subject: "Policy Enforcement: Blocked Device Reconnect",
    body: "Blocked device 3C:71:BF:82:D3:44 attempted to reconnect to the production VLAN.",
    status: "SENT",
    createdAt: new Date(Date.now() - 1000 * 60 * 45),
  },
  {
    id: 3,
    macAddress: null,
    alertType: "SYSTEM_ERROR",
    subject: "System Warning: Scanner Latency",
    body: "The ARP scanner is experiencing higher than normal latency on interface eth0.",
    status: "FAILED",
    createdAt: new Date(Date.now() - 1000 * 60 * 120),
  },
];
